### ISSUE TITLE
Unityバージョンアップ対応

### ISSUE THREAD

**Issue by yzpn00** [koki-yoshimura/Original#12]
## 指定ブランチ
feature/unity_version_up
というブランチを作成しましたので、そちらに切り替えてください。

①Source Tree起動
②「フェッチ」を実行
③リモートから「feature/unity_version_up」をチェックアウト

## 概要
Unityのバージョンアップ

## 指定のバージョン
2018.4.13.f(LTS)

・UnityHubを導入して、そちらからインストールすること
https://unity3d.com/jp/get-unity/download

## 作業項目
- [x] Unity Hub インストール
- [x] Unity Hub上で「Unity 2018.4.13.f(LTS)」インストール
- [x] 新しいバージョンのUnityでこのプロジェクトを起動
- [x] ゲーム動作確認
- [x] バージョンアップによるデータ変更分をpush

**Comment by koki-yoshimura** [comment]
プッシュしました。
バージョンアップ後に文字が画角に収まってないことなどを修正してからプッシュしようと
思いましたが、時間がかかりそうなのでエラーがなおった段階でプッシュさせていただきます。
