### ISSUE TITLE
改修準備

### ISSUE THREAD

**Issue by yzpn00** [koki-yoshimura/Original#3]
## 作業ブランチ
feature/brushup2 をチェックアウト

## 概要
①
Assetsの下に「Scenes」フォルダを用意し、全てのシーンファイルをその中に収納する。

②
小文字から始まっているクラス名のファイルは大文字からに直しましょう。
これもC#のコーディング規約です。

②
＊＊＊Controller.cs 内のソースを、昨日のフィードバック内容を踏まえて整理してください。
変数名の修正、SerializeField化、が主な作業になると思います。

以上が出来たらPull Requestをお願いします。

## 気をつけること
•コミットとpushは一気に全部まとめてやらず、作業ごとにやりましょう。

•これからは、コミットする時のコミット文は「no message」とせず、そのコミットで何をやったかをちゃんと書くようにしましょう。
例: 
○○の追加
○○の更新
○○の○○を修正　など

**Comment by koki-yoshimura** [comment]
SerializeField化、①はやれました。
対応遅くて申し訳ありません。

**Comment by yzpn00** [comment]
>feature/brushup2 をチェックアウト

brushupブランチのほうにpushしていますが
次回から指定のブランチにpushするようにしてくださいね。
